name: trans_bee
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.2.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  intl: ^0.20.2
  http: ^1.1.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.1

  # Updated Firebase packages
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_auth_web: ^6.0.1  # Updated to match firebase_auth
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.3

flutter:
  assets:
    - assets/default_profile.png
    - assets/qr/my_upi_qr.jpeg
    - assets/tr.png
    - assets/tl.png
    - assets/top_animated.jpeg
  uses-material-design: true