// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA69mHyBiMS9PfO96dmQo-MmRWEUVjAU1k',
    appId: '1:474460716855:web:927b327ed9fa1e809424b2',
    messagingSenderId: '474460716855',
    projectId: 'trans-bee',
    authDomain: 'trans-bee.firebaseapp.com',
    storageBucket: 'trans-bee.firebasestorage.app',
    measurementId: 'G-MPPF7N0FX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7FCZa3AEMqr5Ze5_jaVgLDPNe082lc_g',
    appId: '1:474460716855:android:19a473fcf213e9849424b2',
    messagingSenderId: '474460716855',
    projectId: 'trans-bee',
    storageBucket: 'trans-bee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6zwJtpH1JtoeokNtzs6jV-4MHuOSMQmM',
    appId: '1:474460716855:ios:2f6a0ab7b7011ca49424b2',
    messagingSenderId: '474460716855',
    projectId: 'trans-bee',
    storageBucket: 'trans-bee.firebasestorage.app',
    iosBundleId: 'com.example.transBee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6zwJtpH1JtoeokNtzs6jV-4MHuOSMQmM',
    appId: '1:474460716855:ios:2f6a0ab7b7011ca49424b2',
    messagingSenderId: '474460716855',
    projectId: 'trans-bee',
    storageBucket: 'trans-bee.firebasestorage.app',
    iosBundleId: 'com.example.transBee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA69mHyBiMS9PfO96dmQo-MmRWEUVjAU1k',
    appId: '1:474460716855:web:63e2a64b9d18550e9424b2',
    messagingSenderId: '474460716855',
    projectId: 'trans-bee',
    authDomain: 'trans-bee.firebaseapp.com',
    storageBucket: 'trans-bee.firebasestorage.app',
    measurementId: 'G-X096P7WJT3',
  );

}